spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

api.security.token.secret=${JWT_SECRET}
api.security.token.expiration=86400000

#Admin Seed
admin.seed.name=${ADMIN_NAME}
admin.seed.email=${ADMIN_EMAIL}
admin.seed.password=${ADMIN_PASSWORD}