api.security.token.secret=${JWT_SECRET}

route.auth.url=${AUTH_SERVICE_URL:http://med-auth-service:8081}
route.appointment.url=${APPOINTMENT_SERVICE_URL:http://med-appointment-service:8082}
route.clinical.url=${CLINICAL_SERVICE_URL:http://med-clinical-service:8083}
route.document.url=${DOCUMENT_SERVICE_URL:http://med-document-service:8084}