api.security.token.secret=3y46o5HbDTetotSvqqqJdGxGfVaZ6e8DE3gED3lg8Gw

route.auth.url=http://localhost:8081
route.appointment.url=http://localhost:8082
route.clinical.url=http://localhost:8083
route.document.url=http://localhost:8084