spring.application.name=med-gateway
server.port=8080
spring.profiles.active=dev

springdoc.swagger-ui.urls[0].name=1. Autenticação & Identidade
springdoc.swagger-ui.urls[0].url=/api/v1/auth/v3/api-docs

springdoc.swagger-ui.urls[1].name=2. Recepção & Agendamento
springdoc.swagger-ui.urls[1].url=/api/v1/appointments/v3/api-docs

springdoc.swagger-ui.urls[2].name=3. Atendimento Médico
springdoc.swagger-ui.urls[2].url=/api/v1/clinical/v3/api-docs

springdoc.swagger-ui.urls[3].name=4. Documentos
springdoc.swagger-ui.urls[3].url=/api/v1/documents/v3/api-docs