spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# RabbitMQ (Prod)
spring.rabbitmq.host=${RMQ_HOST:rabbitmq-prod}
spring.rabbitmq.port=${RMQ_PORT:5672}
spring.rabbitmq.username=${RMQ_USERNAME}
spring.rabbitmq.password=${RMQ_PASSWORD}